language: python
sudo: required
dist: xenial

cache:
  - directories:
    - $HOME/R/Library
    - /usr/bin/R
    - $HOME/miniconda
    - $HOME/htslib
    - $HOME/bcftools

env:
  global:
    - DROP_DIR=$(pwd)
    - PROJECT_DIR="$HOME/project"
    - MINICONDA_DIR="$HOME/miniconda"
    - CONDA_SCRIPT="$MINICONDA_DIR/etc/profile.d/conda.sh"
    - R_LIBS_USER="$HOME/R/Library"
    - TAR="/bin/tar"

python:
  - "3.6.7"

addons:
  apt:
    packages:
      - r-base
      - libxml2-dev
      - libcurl4-openssl-dev
      - libssl-dev
      - libblas-dev
      - liblapack-dev
      - gfortran
      - graphviz
      - pandoc
      - tabix
    sources:
      - sourceline: 'deb https://cloud.r-project.org/bin/linux/ubuntu xenial-cran35/'
        key_url: 'http://keyserver.ubuntu.com:11371/pks/lookup?op=get&search=0xe298a3a825c0d65dfd57cbb651716619e084dab9'
    update: true
  
install:
  - cd $DROP_DIR
#  - R -e "if ('FRASER' %in% rownames(installed.packages())) remove.packages('FRASER')"
#  - R -e "if ('tMAE' %in% rownames(installed.packages())) remove.packages('tMAE')"
  - Rscript travis/installRPackages.R drop/requirementsR.txt
  - bash travis/install_bcftools.sh
  - export PATH="$HOME/bcftools:$PATH"
  - bcftools --version
  - bash travis/install_conda.sh
  - source $CONDA_SCRIPT
  - conda activate drop_env
  - pip install .

before_script:
  - mkdir -p $PROJECT_DIR
  - cd $PROJECT_DIR
  - drop demo

script: true
  - cd $PROJECT_DIR
  - snakemake -n
  - snakemake aberrantExpression --cores 2
  - snakemake aberrantSplicing --cores 2
  - snakemake mae --cores 2
  - snakemake --cores 2
  - snakemake exportCounts --cores 2
