language: python
dist: xenial

#cache:
#  - directories:
#    - $HOME/miniconda

python:
  - "3.7"

install:
  # Install Anaconda
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O /tmp/miniconda.sh
  - bash /tmp/miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda

  # install dependencies
  - source $HOME/miniconda/etc/profile.d/conda.sh
  - conda create -q -n drop -c conda-forge -c bioconda drop
  - conda activate drop

  # install drop
  - pip install -e .

script: 
  - conda list 
  - java -version
  - gatk --help
  - samtools --version
  - bcftools --version
  - drop --version
  - python --version
  
  - mkdir drop_demo
  - cd drop_demo
  - drop demo
  - snakemake -n
  - snakemake --jobs 2 --cores 2
