name: drop_test
channels:
  - conda-forge
  - bioconda
dependencies:
  - python==3.8
  - pip
  - drop
  - flake8
  - bioconductor-bsgenome.hsapiens.ucsc.hg19
  - samtools>=1.9
  - bcftools>=1.9
  - wbuild>=1.8
