name: drop

channels:
  - bioconda
  - conda-forge
  - anaconda

dependencies:
    # core python
    #- python=3.7
    - pandas
    - pip>=19.1
    - Click>=7.0
    - click-log
    - python-dateutil
    - git

    # snakemake
    - snakemake=>5.5.2
    - pandoc
    - graphviz

    # command line tools
    - tabix
    - samtools>=1.7
    - bcftools>=1.7
    - gatk4>=4.0.4
    - star>=2.7

    # R dependencies
    - r-base>=4.0.0
    - r-rmarkdown
    - r-knitr
    - r-ggplot2
    - r-ggthemes
    - r-cowplot
    - r-data.table
    - r-dplyr
    - r-tidyr
    - r-magrittr
    - r-devtools
    
    # bioconductor packages
    - bioconductor-deseq2
    - bioconductor-GenomicScores
    - bioconductor-outrider
    - bioconductor-fraser
    - bioconductor-variantannotation
    - bioconductor-bsgenome.hsapiens.ucsc.hg19
      #- bioconductor-mafdb.gnomad.r2.1.hs37d5
      #- bioconductor-mafdb.gnomad.r2.1.grch38
    #mumichae/tMAE TRUE

    - pip:
        - wbuild @ git+https://github.com/gagneurlab/wBuild.git@master#egg=wbuild
        #- drop   @ git+https://github.com/gagneurlab/drop.git@master#egg=drop


