name: Build

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
#    container:
#      image: mambaorg/micromamba:latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup environment with micromamba
      uses: mamba-org/provision-with-micromamba@v10

    - name: Check micromamba install
      shell: bash -l {0}
      run: |
        micromamba --version
        micromamba env list

#    - name: Install dependencies
#      run: mamba env update -f environment.yml

    - name: Lint with flake8
      shell: bash -l {0}
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --builtins="snakemake" --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Install DROP
      shell: bash -l {0}
      run: pip install -e .

    - name: Test with pytest
      shell: bash -l {0}
      env:
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      run: |
        micromamba install pytest
        pip install -r tests/requirements.txt
        pytest
